#!/bin/bash

SCRIPT_DIR=$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )
source $SCRIPT_DIR/../src/yaml
YAML_FILENAME=$SCRIPT_DIR/sample.yml

# Define tests
function test_reading_values() {
    yaml=$(cat $YAML_FILENAME)
    [ "$(echo "$yaml" | yaml_get_value author.name)" == "Djordje Ungar" ] &&
    [ "$(echo "$yaml" | yaml_get_value author.username)" == "artbit" ] &&
    [ "$(echo "$yaml" | yaml_get_value author.email)" == 'artbit@email.com' ] &&
    return 0 || return 1
}
function test_dumbl() {
    dumbl=$(cat $YAML_FILENAME | yaml_to_dumbl)
    [ "$(echo "$dumbl" | grep '^author.name' )" == "author.name: Djordje Ungar" ] &&
    [ "$(echo "$dumbl" | grep '^author.username' )" == "author.username: artbit" ] &&
    [ "$(echo "$dumbl" | grep '^author.email' )" == "author.email: artbit@email.com" ] &&
    return 0 || return 1
}
function test_replacing_values() {
    replaced=$(cat $YAML_FILENAME | yaml_replace 'author.name' 'Anonymous' | yaml_replace 'author.email' 'someone@email.com')
    [ "$(echo "$replaced" | yaml_get_value author.name )" == "Anonymous" ] &&
    [ "$(echo "$replaced" | yaml_get_value author.username )" == "artbit" ] &&
    [ "$(echo "$replaced" | yaml_get_value author.email )" == "someone@email.com" ] &&
    return 0 || return 1
}
function test_parse() {
    yaml=$(cat $YAML_FILENAME)
    eval "$(echo "$yaml" | yaml_parse author.name --prefix test)"
    eval "$(echo "$yaml" | yaml_parse author.username --prefix test)"
    eval "$(echo "$yaml" | yaml_parse author.email --prefix test)"
    [ "$test_author_name" == "Djordje Ungar" ] &&
    [ "$test_author_username" == "artbit" ] &&
    [ "$test_author_email" == "artbit@email.com" ] &&
    return 0 || return 1
}
